"""Config command: initialize and manage podifyr configuration."""

from __future__ import annotations

from pathlib import Path

import typer

from podifyr.cli.display import console


def config_init(
    output: Path = typer.Option(
        Path(".env"),
        "--output", "-o",
        help="Path to write the configuration file.",
    ),
    force: bool = typer.Option(
        False,
        "--force", "-f",
        help="Overwrite existing configuration file.",
    ),
) -> None:
    """Initialize a new .env configuration file with default values."""
    if output.exists() and not force:
        console.print(
            f"[warning]Configuration file already exists:[/warning] {output}\n"
            "Use --force to overwrite."
        )
        raise typer.Exit(code=1)

    template = _get_config_template()

    try:
        output.write_text(template, encoding="utf-8")
        console.print(f"[success]✓ Configuration written to:[/success] [cyan]{output}[/cyan]")
        console.print("[dim]Edit the file to add your API keys and customize settings.[/dim]")
    except OSError as exc:
        console.print(f"[error]Failed to write config:[/error] {exc}")
        raise typer.Exit(code=1) from exc


def config_show() -> None:
    """Display the current resolved configuration (secrets redacted)."""
    from rich.table import Table

    from podifyr.config import get_settings

    settings = get_settings()

    table = Table(title="Current Configuration", show_header=True)
    table.add_column("Setting", style="dim")
    table.add_column("Value", style="cyan")

    # API keys (redacted)
    openai_key = settings.effective_openai_key
    table.add_row(
        "OpenAI API Key",
        f"{openai_key[:8]}...{openai_key[-4:]}" if len(openai_key) > 12 else "[red]NOT SET[/red]",
    )

    el_key = settings.elevenlabs_api_key
    table.add_row(
        "ElevenLabs API Key",
        f"{el_key[:8]}...{el_key[-4:]}" if len(el_key) > 12 else "[dim]not set[/dim]",
    )

    # LLM settings
    table.add_row("LLM Model", settings.llm.model)
    table.add_row("LLM Temperature", str(settings.llm.temperature))
    table.add_row("LLM Max Tokens", str(settings.llm.max_tokens))

    # TTS settings
    table.add_row("TTS Backend", settings.tts.backend)
    table.add_row("TTS Voice", settings.tts.voice)
    table.add_row("TTS Model", settings.tts.model)
    table.add_row("Max Concurrent", str(settings.tts.max_concurrent_requests))

    # Cache
    table.add_row("Cache Enabled", "Yes" if settings.cache.enabled else "No")
    table.add_row("Cache TTL", f"{settings.cache.ttl_seconds}s")

    # Logging
    table.add_row("Log Level", settings.logging.level)
    table.add_row("Log Format", settings.logging.format)

    console.print(table)


def _get_config_template() -> str:
    """Return the .env template content."""
    return """\
# ─── Podifyr Configuration ───────────────────────────────────────────────────
# Generated by: podifyr config init

# Required: OpenAI API key for LLM (not needed if using Azure or edge TTS)
OPENAI_API_KEY=sk-your-key-here

# Optional: ElevenLabs API key (for elevenlabs TTS backend)
# ELEVENLABS_API_KEY=

# ─── LLM Settings ───────────────────────────────────────────────────────────
PODIFYR_LLM_MODEL=gpt-4o-mini
PODIFYR_LLM_TEMPERATURE=0.3
PODIFYR_LLM_MAX_TOKENS=2048

# ─── Audio Settings ─────────────────────────────────────────────────────────
PODIFYR_TTS_BACKEND=edge
# Options: edge (free, no API key), openai, elevenlabs
PODIFYR_TTS_VOICE=alloy
# OpenAI voices: alloy, echo, fable, onyx, nova, shimmer
# Edge TTS maps these automatically to Microsoft neural voices
PODIFYR_TTS_MODEL=tts-1
PODIFYR_MAX_CONCURRENT_REQUESTS=5

# ─── Azure OpenAI (optional, replaces public OpenAI) ────────────────────────
# PODIFYR_AZURE_ENABLED=true
# PODIFYR_AZURE_ENDPOINT=https://your-resource.openai.azure.com
# PODIFYR_AZURE_API_KEY=your-azure-key
# PODIFYR_AZURE_API_VERSION=2024-12-01-preview
# PODIFYR_AZURE_CHAT_DEPLOYMENT=gpt-4o-mini

# ─── Cache Settings ─────────────────────────────────────────────────────────
PODIFYR_CACHE_ENABLED=true
PODIFYR_CACHE_TTL_SECONDS=86400

# ─── Logging ────────────────────────────────────────────────────────────────
PODIFYR_LOG_LEVEL=INFO
PODIFYR_LOG_FORMAT=console
# Options: console, json
"""
